name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
    
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=python-project-50 --cov-report=xml
            
      - name: Upload coverage to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          bash <(curl -s https://codeclimate.com/test_reports) > cc-test-reporter
          ./cc-test-reporter after-build --exit-code $?
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run isort
        run: poetry run isort --check --diff .
